### ISSUE TITLE
Bug with concurrent interleaved inserts

### ISSUE THREAD

**Issue by jclem** [jure/rgass#1]
I also have been implementing RGASS recently, although in TypeScript instead of JavaScript. One of several issues I found with the algorithm described paper is that it seems to break with concurrent interleaving inserts, and I've noticed this implementation has the same bug (I haven't found a way around it yet, either).

I've illustrated it in this drawing (where ops are `[type, targetKey, key, pos, text]` and keys are `[session, site, ssv, offset, length]`):
 
![img_2079](https://cloud.githubusercontent.com/assets/412282/26171701/efeb8f76-3b13-11e7-9d65-31a219901824.JPG)

1. Site *1* sends an operation inserting "abcd" into the blank document, which site *2* integrates without issue. This operation is `{ type: 'insert', targetKey: null, key: { session: 1, site: 1, ssv: 1, offset: 0, length: 4 }, position: 0, text: 'abcd' }`.
2. A network partition occurs, during which:
    1. Site *2* inserts "X" between "b" and "c" and splits the "abcd" node in half.
    2. Site *1* inserts "Y" between "a" and "b", splitting the "abcd" node.
    3. Site *1* inserts "Z" between "c" and "d", splitting the "bcd" node.
3. Network is back, and site *1* sends its operations to site *2* (we can ignore site *2*'s pending operation):
    1. The first operation, `{ type: 'insert', targetKey: { session: 1, site: 1, ssv: 1, offset: 0, length: 4 }, key: { session: 1, site: 1, ssv: 2, offset: 0, length: 1 }, position: 1, text: 'Y' }` arrives and is successfully integrated.
    2. The second operation, `{ type: 'insert', targetKey: { session: 1, site: 1, ssv: 1, offset: 1, length: 3 }, key: { session: 1, site: 1, ssv: 3, offset: 0, length: 1 }, position: 2, text: 'Z' }` arrives. However, no such target node exists because it was already split by site *2*'s operation in which it inserted an "X". The target node `{ session: 1, site: 1, ssv: 1, offset: 1, length: 3 }` never existed, because its length on client *2* was never 3.

Perhaps I'm completely misunderstanding something, but this seems to be a significant issue with RGASS. I've also reached out to Fazhi He, one of the authors of the paper (and now also linked them to this issue), but haven't heard back yet.

**Comment by jclem** [comment]
I should note that while `{ session: 1, site: 1, ssv: 1, offset: 1, length: 1 }` *does* exist at site *2*, it's in a different subtree than where the incoming operation actually needs to be inserted, meaning that in order to find the proper location, we'd actually have to start at the node that matches `{ session: 1, site: 1, ssv: 1, offset: 0 }` with the longest length (the original one) and then search for the target location from there, which I do not believe is what the paper has in mind.

**Comment by jclem** [comment]
One more thing: I think all of this, and a bunch of other bugs in RGASS, can be avoided by generating operations relative to "base" nodes, rather than relative to only visible nodes. E.g. if an edit is inside of a node that resulted from a split, write the operation such that it refers to the base node (which may be up several levels of splits).

**Comment by jure** [comment]
Oh my, this is so awesome! @jclem, I'm sorry I missed your issue, and for five months! This looks like an accurate description of the problem, there's also a problem with deletions (check out the failing test at: https://github.com/jure/rgass/blob/master/test/rgass_test.js#L1007)

I've been in touch with this researcher from Norway, who solved it, but in Lisp.

This is what I sent to him: "I've come across your work while implementing a block-based RGA based on this paper: http://www.sciencedirect.com/science/article/pii/S1474034616301811. However, I found that this algorithm seemingly doesn't address the situation which you point out in your paper https://hal.inria.fr/hal-01246212/document here:

"A remote deletion specifies the inner nodes of the deletion at the time of its creation. The referent inner nodes at the current peer may differ from the specified ones in two ways: (1) the remote peer might have split the inner nodes at deletion boundaries (as shown with the upward arrows in Fig. 2-1); (2) the current peer might have split the inner nodes when integrating concurrent operations (as shown with the downward arrows in Fig. 2-1)."

Since you've addressed this in your algorithm, I was wondering if it would be possible for you to share your implementation/source code. I'm not currently interested in undo (though that feature will likely come up in the future), but I am interested in resolving this concurrent node-splitting issue."

Check out http://www.cs.uit.no/~weihai/selective-undo-in-wyde.mkv

I'll ask him if I (or he) can share the code here, so we have a starting point.

**Comment by jclem** [comment]
No problem! Glad you saw this.

The current version of my implementation is at https://github.com/jclem/crdt/tree/master/rgass. It's a little messy (I decided to port my old implementation from JS to Go for no good reason) and in need of some fuzz testing, but I think I'm circumventing the concurrency issue by requiring remote operations to be broadcast only with original (non-split) nodes. This is relatively efficient for the broadcaster, because I track `node.Ancestor` and `node.AncestorOffset`, which represent the most distant non-split ancestor of a node, and the total offset for any given node from its most distant non-split ancestor, respectively.

**Comment by jure** [comment]
@jclem: turns out the issue you present here isn't an issue with this implementation. I added a test here with the exact same scenario: https://github.com/jure/rgass/pull/2 and it passes. However, I do remember coming across this problem and solving it differently to what is presented in the paper. I'll try to find what the exact difference is.

Unfortunately the issue of overlapping concurrent deletes still remains.
